version: '3.8'
services:
  pgadmin:
    build: .
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin12345
    restart: unless-stopped 