FROM dpage/pgadmin4:latest

# Установка переменных окружения для pgAdmin
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=admin12345
ENV PGADMIN_CONFIG_SERVER_MODE=False
ENV PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False

# Экспозиция порта
EXPOSE 80 